import React, { useState } from "react";
import { Meta } from "@storybook/react";
import Icon, { IconName } from "../../components/Icons/Icon";
import { InputSearch } from "../../components";

export default {
  title: "Components/Icons",
  component: Icon,
} as Meta;

const icons = [
  "activity",
  "airplay",
  "alert-circle",
  "alert-octagon",
  "alert-triangle",
  "align-center",
  "align-justify",
  "align-left",
  "align-right",
  "anchor",
  "aperture",
  "archive",
  "arrow-down",
  "arrow-down-circle",
  "arrow-down-left",
  "arrow-down-right",
  "arrow-left",
  "arrow-left-circle",
  "arrow-right",
  "arrow-right-circle",
  "arrow-up",
  "arrow-up-circle",
  "arrow-up-left",
  "arrow-up-right",
  "at-sign",
  "award",
  "bar-chart",
  "bar-chart-2",
  "battery",
  "battery-charging",
  "bell",
  "bell-off",
  "bluetooth",
  "bold",
  "book",
  "book-open",
  "bookmark",
  "box",
  "briefcase",
  "calendar",
  "camera",
  "camera-off",
  "cast",
  "check",
  "check-circle",
  "check-square",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  "chevron-up",
  "chevrons-down",
  "chevrons-left",
  "chevrons-right",
  "chevrons-up",
  "chrome",
  "circle",
  "clipboard",
  "clock",
  "cloud",
  "cloud-drizzle",
  "cloud-lightning",
  "cloud-off",
  "cloud-rain",
  "cloud-snow",
  "code",
  "codepen",
  "codesandbox",
  "coffee",
  "columns",
  "command",
  "compass",
  "copy",
  "corner-down-left",
  "corner-down-right",
  "corner-left-down",
  "corner-left-up",
  "corner-right-down",
  "corner-right-up",
  "corner-up-left",
  "corner-up-right",
  "cpu",
  "credit-card",
  "crop",
  "crosshair",
  "database",
  "delete",
  "disc",
  "dollar-sign",
  "download",
  "download-cloud",
  "droplet",
  "edit",
  "edit-2",
  "edit-3",
  "external-link",
  "eye",
  "eye-off",
  "facebook",
  "fast-forward",
  "feather",
  "figma",
  "file",
  "file-minus",
  "file-plus",
  "file-text",
  "film",
  "filter",
  "flag",
  "folder",
  "folder-minus",
  "folder-plus",
  "framer",
  "frown",
  "gift",
  "git-branch",
  "git-commit",
  "git-merge",
  "git-pull-request",
  "github",
  "gitlab",
  "globe",
  "grid",
  "hard-drive",
  "hash",
  "headphones",
  "heart",
  "help-circle",
  "hexagon",
  "home",
  "image",
  "inbox",
  "info",
  "instagram",
  "italic",
  "key",
  "layers",
  "layout",
  "life-buoy",
  "link",
  "link-2",
  "linkedin",
  "list",
  "loader",
  "lock",
  "log-in",
  "log-out",
  "mail",
  "map",
  "map-pin",
  "maximize",
  "maximize-2",
  "meh",
  "menu",
  "message-circle",
  "message-square",
  "mic",
  "mic-off",
  "minimize",
  "minimize-2",
  "minus",
  "minus-circle",
  "minus-square",
  "monitor",
  "moon",
  "more-horizontal",
  "more-vertical",
  "mouse-pointer",
  "move",
  "music",
  "navigation",
  "navigation-2",
  "octagon",
  "package",
  "paperclip",
  "pause",
  "pause-circle",
  "pen-tool",
  "percent",
  "phone",
  "phone-call",
  "phone-forwarded",
  "phone-incoming",
  "phone-missed",
  "phone-off",
  "phone-outgoing",
  "pie-chart",
  "play",
  "play-circle",
  "plus",
  "plus-circle",
  "plus-square",
  "pocket",
  "power",
  "printer",
  "radio",
  "refresh-ccw",
  "refresh-cw",
  "repeat",
  "rewind",
  "rotate-ccw",
  "rotate-cw",
  "rss",
  "save",
  "scissors",
  "search",
  "send",
  "server",
  "settings",
  "share",
  "share-2",
  "shield",
  "shield-off",
  "shopping-bag",
  "shopping-cart",
  "shuffle",
  "sidebar",
  "skip-back",
  "skip-forward",
  "slack",
  "slash",
  "sliders",
  "smartphone",
  "smile",
  "speaker",
  "square",
  "star",
  "stop-circle",
  "sun",
  "sunrise",
  "sunset",
  "tablet",
  "tag",
  "target",
  "terminal",
  "thermometer",
  "thumbs-down",
  "thumbs-up",
  "toggle-left",
  "toggle-right",
  "tool",
  "trash",
  "trash-2",
  "trello",
  "trending-down",
  "trending-up",
  "triangle",
  "truck",
  "tv",
  "twitch",
  "twitter",
  "type",
  "umbrella",
  "underline",
  "unlock",
  "upload",
  "upload-cloud",
  "user",
  "user-check",
  "user-minus",
  "user-plus",
  "user-x",
  "users",
  "video",
  "video-off",
  "voicemail",
  "volume",
  "volume-1",
  "volume-2",
  "volume-x",
  "watch",
  "wifi",
  "wifi-off",
  "wind",
  "x",
  "x-circle",
  "x-octagon",
  "x-square",
  "youtube",
  "zap",
  "zap-off",
  "zoom-in",
  "zoom-out",
  "heart1",
  "cloud1",
  "star1",
  "trash1",
  "user1",
  "key1",
  "search1",
  "settings1",
  "tag1",
  "lock1",
  "pen",
  "display",
  "location",
  "eye1",
  "bubble",
  "stack",
  "phone1",
  "mail1",
  "like",
  "params",
  "banknote",
  "t-shirt",
  "fire",
  "clip",
  "shop",
  "calendar1",
  "wallet",
  "truck1",
  "world",
].sort((icon1, icon2) => {
  if (icon1 > icon2) return 1;
  if (icon1 < icon2) return -1;
  return 0;
});

export const IconList = () => {
  const handleCopy = async (iconName: string) => {
    await navigator.clipboard.writeText(`<Icon name="${iconName}" />`);
    alert(`${iconName} copied`);
  };

  const [query, setQuery] = useState("");

  const handleFilter = async (iconName: string) => {
    setQuery(iconName);
  };

  const filteredIcons = icons.filter((icon) => icon.includes(query));

  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        gap: "10px",
      }}
    >
      <div>
        <InputSearch
          textFieldProps={{ style: { width: "100%" } }}
          onChange={handleFilter}
        />
      </div>
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(6, 1fr)",
          gap: "10px",
          padding: "10px",
        }}
      >
        {filteredIcons.map((iconName) => (
          <button
            key={iconName}
            onClick={() => handleCopy(iconName)}
            style={{
              cursor: "pointer",
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              gap: "10px",
              padding: "10px",
            }}
          >
            <Icon name={iconName as IconName} size={32} />
            <span>{iconName}</span>
            <div
              style={{ backgroundColor: "white", padding: 2, fontSize: "12px" }}
            >
              <code>{`<Icon name="${iconName}" />`}</code>
            </div>
          </button>
        ))}
      </div>
    </div>
  );
};
